Repository aleph-im/aleph-sdk-python, pull requests merged in 2023-11, with the labels that each got.

#77 Add allow_amend, internet and aleph_api parameters to create_program
  src/aleph/sdk/client/abstract.py
  src/aleph/sdk/client/authenticated_http.py
Labels: BLUE

#78 Add `create_instance` method
  src/aleph/sdk/client/abstract.py
  src/aleph/sdk/client/authenticated_http.py
  tests/unit/test_asynchronous.py
Labels: RED

#80 Update PR Difficulty Rating action to always use the latest version.
  .github/workflows/pr-rating.yml
Labels: BLACK

#55 Feature : AlephDNS (2nd attempt)
  setup.cfg
  src/aleph/sdk/conf.py
  src/aleph/sdk/domain.py
  src/aleph/sdk/exceptions.py
  tests/unit/test_domains.py
Labels: RED

#81 Refactor: Simplify and improve `get_messages`; use mocked responses
  src/aleph/sdk/client/abstract.py
  src/aleph/sdk/client/http.py
  src/aleph/sdk/exceptions.py
  tests/unit/conftest.py
  tests/unit/post.json
  tests/unit/test_asynchronous.py
  tests/unit/test_asynchronous_get.py
Labels: RED

#84 Use `extended_json_encoder` as default in `ClientSession`
  src/aleph/sdk/client/authenticated_http.py
  src/aleph/sdk/client/http.py
  src/aleph/sdk/utils.py
  tests/unit/test_asynchronous.py
  tests/unit/test_utils.py
Labels: BLACK
