Repository aleph-im/aleph-sdk-python, pull requests merged in 2024-07, with the labels that each got.

#138 Implement `VmConfidentialClient` class
  pyproject.toml
  src/aleph/sdk/client/vm_client.py
  src/aleph/sdk/client/vm_confidential_client.py
  src/aleph/sdk/types.py
  src/aleph/sdk/utils.py
  tests/unit/aleph_vm_authentication.py
  tests/unit/test_vm_client.py
  tests/unit/test_vm_confidential_client.py
Labels: BLACK

#139 ci: remove macos-11 build since it's not supported anymore
  .github/workflows/build-wheels.yml
Labels: BLUE

#137 Add new Confidential fields
  src/aleph/sdk/client/abstract.py
  src/aleph/sdk/client/authenticated_http.py
  tests/unit/test_asynchronous.py
Labels: RED

#141 Fix typo
  src/aleph/sdk/client/vm_confidential_client.py
Labels: BLUE

#142 Fix: Bump aleph-message version to 0.4.8
  pyproject.toml
Labels: BLUE
