Repository aleph-im/aleph-sdk-python, pull requests merged in 2024-11, with the labels that each got.

#182 Implement new EVM chains
  .github/workflows/build-wheels.yml
  .gitignore
  pyproject.toml
  src/aleph/sdk/account.py
  src/aleph/sdk/chains/evm.py
  src/aleph/sdk/conf.py
  src/aleph/sdk/evm_utils.py
  src/aleph/sdk/types.py
Labels: BLACK

#184 Fix wrong account config alert
  src/aleph/sdk/account.py
Labels: BLACK

#189 Fix wrong chain account loading
  src/aleph/sdk/account.py
Labels: BLUE

#188 Add missing env var placeholders for new EVM chains
  src/aleph/sdk/conf.py
Labels: RED

#187 Fix get_message_status #186
  src/aleph/sdk/client/http.py
Labels: BLACK
