Repository aleph-im/aleph-sdk-python, pull requests merged in 2025-04, with the labels that each got.

#213 Feature: New SVMAccount
  src/aleph/sdk/account.py
  src/aleph/sdk/chains/svm.py
  tests/unit/test_chain_svm.py
Labels: BLACK

#212 Update `web3` dependency
  pyproject.toml
  src/aleph/sdk/chains/ethereum.py
  src/aleph/sdk/evm_utils.py
Labels: RED

#214 Increase superfluid fork dependency version
  pyproject.toml
  src/aleph/sdk/account.py
Labels: BLUE
